Repository PSR-Co/FRONTEND, pull requests merged in 2023-08, with the labels that each got.

#40 [Config] 네트워크 통신 환경설정
  lib/auth/view/login_screen.dart
  lib/common/const/constants.dart
  lib/common/view/search_screen.dart
  lib/common/view/splash_screen.dart
  lib/main.dart
  lib/model/data/auth/auth_model.dart
  lib/model/data/auth/auth_model.g.dart
  lib/model/data/general_model.dart
  lib/model/data/shopping/product_model.dart
  lib/model/data/shopping/product_model.g.dart
  lib/model/network/api_manager.dart
  lib/model/network/constants.dart
  lib/presenter/auth/auth_service.dart
  lib/presenter/shopping/shopping_service.dart
  lib/shopping/component/category_list_item.dart
  lib/shopping/component/popular_list_item.dart
  lib/shopping/component/tabbar_widget.dart
  lib/shopping/view/shopping_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ⚙️config

#42 [Fix] 마이페이지 요청목록 요청 카드 내 프로필 이미지 제거
  asset/icons/common/heart.svg
  lib/mypage/component/action_btn.dart
  lib/mypage/component/detail_order_textfield_form.dart
  lib/mypage/component/notification_list_item.dart
  lib/mypage/component/order_list_item.dart
  lib/mypage/view/detail_order_screen.dart
  lib/mypage/view/likelist_screen.dart
  lib/mypage/view/mypage_screen.dart
  lib/mypage/view/mypost_screen.dart
  lib/mypage/view/notificationlist_screen.dart
  lib/mypage/view/order_list_tab.dart
  lib/mypage/view/orderlist_screen.dart
  lib/mypage/view/seller_detail_order_screen.dart
Labels: 🛠fix

#45 [Feature] 자주 묻는 질문 API 연결
  lib/cs/component/faq_tabbar_widget.dart
  lib/cs/component/inquiry_list.dart
  lib/cs/component/notice_list.dart
  lib/cs/view/admin_detail_inquiry_screen.dart
  lib/cs/view/detail_faq_screen.dart
  lib/cs/view/detail_inquiry_screen.dart
  lib/cs/view/detail_notice_screen.dart
  lib/cs/view/faq_screen.dart
  lib/cs/view/inquiry_screen.dart
  lib/cs/view/notice_screen.dart
  lib/cs/view/service_center_screen.dart
  lib/home/component/notice_list_content.dart
  lib/home/component/recent_list_item.dart
  lib/home/view/home_screen.dart
  lib/model/data/cs/detail_notice_model.dart
  lib/model/data/cs/detail_notice_model.g.dart
  lib/model/data/cs/faq_model.dart
  lib/model/data/cs/faq_model.g.dart
  lib/model/data/cs/notice_model.dart
  lib/model/data/cs/notice_model.g.dart
  lib/model/network/api_manager.dart
  lib/mypage/view/mypage_screen.dart
  lib/presenter/cs/cs_service.dart
  lib/servicecenter/component/faq_list.dart
  lib/servicecenter/view/faq_screen.dart
  lib/servicecenter/view/notice_screen.dart
Labels: 🔗feature

#47 [Feature] Auth API 연결 중 임시저장
  lib/auth/component/input_user_info.dart
  lib/auth/component/reset_password.dart
  lib/auth/view/find_id_screen.dart
  lib/auth/view/find_pw_screen.dart
  lib/auth/view/login_screen.dart
  lib/auth/view/show_user_id_screen.dart
  lib/auth/view/signup/input_accout_info_screen.dart
  lib/auth/view/signup/input_business_info_screen.dart
  lib/auth/view/signup/input_user_info_screen.dart
  lib/auth/view/signup/select_interest_screen.dart
  lib/auth/view/signup/select_role_screen.dart
  lib/auth/view/signup/set_profile_screen.dart
  lib/common/layout/purple_outlined_text_field.dart
  lib/model/data/auth/auth_model.dart
  lib/model/data/auth/auth_model.g.dart
  lib/model/data/auth/login_model.dart
  lib/model/data/auth/login_model.g.dart
  lib/model/data/auth/signup_model.dart
  lib/model/data/auth/signup_model.g.dart
  lib/model/data/auth/user_model.dart
  lib/model/data/auth/user_model.g.dart
  lib/model/data/general_model.dart
  lib/model/data/general_model.g.dart
  lib/model/network/api_manager.dart
  lib/myinfo/view/myinfo_screen.dart
  lib/presenter/auth/auth_service.dart
  lib/presenter/auth/login_service.dart
  lib/presenter/auth/signup_service.dart
  lib/presenter/auth/user_service.dart
Labels: 🔗feature

#48 [Feature] 홈화면 공지사항 API 연결
  lib/cs/view/detail_notice_screen.dart
  lib/home/component/notice_list_content.dart
  lib/model/data/cs/detail_notice_model.dart
  lib/model/data/cs/detail_notice_model.g.dart
  lib/model/data/cs/home_notice_model.dart
  lib/model/data/cs/home_notice_model.g.dart
  lib/model/data/cs/notice_model.dart
  lib/model/data/cs/notice_model.g.dart
  lib/presenter/cs/cs_service.dart
Labels: 🔗feature

#50 [Feature]홈화면 API 연결
  lib/home/component/best_list_item.dart
  lib/home/component/fav_package_footer_item.dart
  lib/home/component/favorite_package_list_item.dart
  lib/home/component/notice_list_content.dart
  lib/home/component/product_list_item.dart
  lib/home/component/recent_list_item.dart
  lib/home/view/home_screen.dart
  lib/model/data/home/home_model.dart
  lib/model/data/home/home_model.g.dart
  lib/presenter/home/home_service.dart
Labels: 🔗feature

#51 [Feature] Auth API 연결
  lib/auth/component/account_input_text_field.dart
  lib/auth/component/input_account_info.dart
  lib/auth/view/signup/input_accout_info_screen.dart
  lib/auth/view/signup/input_business_info_screen.dart
  lib/auth/view/signup/set_profile_screen.dart
  lib/common/layout/purple_outlined_textfield_with_button.dart
  lib/model/data/auth/signup_model.dart
  lib/model/data/auth/signup_model.g.dart
  lib/model/data/auth/user_model.dart
  lib/model/data/auth/user_model.g.dart
  lib/model/network/constants.dart
  lib/myinfo/view/myinfo_screen.dart
  lib/presenter/auth/signup_service.dart
  lib/presenter/auth/user_service.dart
Labels: 🔗feature

#53 [Fix] part (of) 키워드 수정
  lib/home/component/best_list_item.dart
  lib/home/component/notice_list_content.dart
  lib/home/component/recent_list_item.dart
  lib/home/view/home_screen.dart
  lib/model/data/cs/home_notice_model.dart
  lib/model/data/cs/home_notice_model.g.dart
  lib/model/data/home/home_model.dart
  lib/model/data/home/home_model.g.dart
Labels: 🛠fix

#55 [Feature] Products API 연결
  lib/auth/component/complete_widget.dart
  lib/common/layout/purple_filled_button.dart
  lib/common/layout/purple_outlined_text_field.dart
  lib/common/view/search_screen.dart
  lib/model/data/cs/faq_model.g.dart
  lib/model/data/cs/home_notice_model.g.dart
  lib/model/data/cs/notice_model.g.dart
  lib/model/data/home/home_model.g.dart
  lib/model/data/shopping/order_request_model.dart
  lib/model/data/shopping/order_request_model.g.dart
  lib/model/data/shopping/product_model.dart
  lib/model/data/shopping/product_model.g.dart
  lib/model/data/shopping/review_model.dart
  lib/model/data/shopping/review_model.g.dart
  lib/model/data/shopping/shopping_main_model.dart
  lib/model/data/shopping/shopping_main_model.g.dart
  lib/model/data/shopping/user_product_model.dart
  lib/model/data/shopping/user_product_model.g.dart
  lib/model/network/api_manager.dart
  lib/order/component/order_info_input_widget.dart
  lib/order/view/add_order_screen.dart
  lib/order/view/complete_order_screen.dart
  lib/presenter/shopping/shopping_service.dart
  lib/product/component/bottom_navigation_widget.dart
  lib/product/component/custom_dropdown_button.dart
  lib/product/component/product_detail_appbar.dart
  lib/product/component/product_detail_widget.dart
  lib/product/component/product_img_page_view_widget.dart
  lib/product/component/review_list_item.dart
  lib/product/component/review_list_widget.dart
  lib/product/component/seller_info_widget.dart
  lib/product/component/seller_product_list_item.dart
  lib/product/view/add_product_screen.dart
  lib/product/view/declaration_dialog.dart
  lib/product/view/product_detail_screen.dart
  lib/product/view/seller_profile_screen.dart
  lib/review/component/review_info_widget.dart
  lib/shopping/component/category_list_item.dart
  lib/shopping/component/popular_list_item.dart
  lib/shopping/component/tabbar_widget.dart
Labels: 🔗feature

#57 [Feature] Orders API 연결
  lib/common/const/constants.dart
  lib/home/view/home_screen.dart
  lib/model/data/order/edit_order_model.dart
  lib/model/data/order/edit_order_model.g.dart
  lib/model/data/order/order_detail_model.dart
  lib/model/data/order/order_detail_model.g.dart
  lib/model/data/order/order_list_model.dart
  lib/model/data/order/order_list_model.g.dart
  lib/model/network/api_manager.dart
  lib/mypage/component/MoveToDetailOrderScreen.dart
  lib/mypage/component/detail_order_textfield_form.dart
  lib/mypage/component/mypage.dart
  lib/mypage/component/order_list_item.dart
  lib/mypage/view/detail_order_screen.dart
  lib/mypage/view/mypage_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/mypage/view/order_list_tab.dart
  lib/mypage/view/orderlist_screen.dart
  lib/mypage/view/seller_detail_order_screen.dart
  lib/presenter/cs/cs_service.dart
  lib/presenter/order/order_service.dart
Labels: 🔗feature

#59 [Feature] 검색 결과 정렬 버튼 추가
  lib/common/view/search_screen.dart
Labels: 🔗feature

#62 [Feature] Inquiry API 연결
  lib/common/layout/large_detail_bar_layout.dart
  lib/cs/view/admin_detail_inquiry_screen.dart
  lib/cs/view/inquiry_screen.dart
  lib/cs/view/service_center_screen.dart
  lib/home/view/home_screen.dart
  lib/model/data/inquiry/add_inquiry_answer_model.dart
  lib/model/data/inquiry/add_inquiry_answer_model.g.dart
  lib/model/data/inquiry/inquiry_detail_model.dart
  lib/model/data/inquiry/inquiry_detail_model.g.dart
  lib/model/data/inquiry/inquiry_list_model.dart
  lib/model/data/inquiry/inquiry_list_model.g.dart
  lib/model/data/inquiry/inquiry_model.dart
  lib/model/data/inquiry/inquiry_model.g.dart
  lib/model/data/order/order_list_model.dart
  lib/model/data/order/order_list_model.g.dart
  lib/myinfo/component/complete_btn.dart
  lib/myinfo/view/change_interest_screen.dart
  lib/myinfo/view/change_profile_screen.dart
  lib/myinfo/view/change_pw_screen.dart
  lib/mypage/view/detail_order_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/presenter/inquiry/inquiry_service.dart
Labels: 🔗feature

#67 [Config] Firebase Storage 사용을 위한 환경설정 및 사용 코드 추가
  .gitignore
  android/app/build.gradle
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/main.dart
  lib/model/network/constants.dart
  lib/presenter/common/ImageService.dart
  lib/product/component/product_img_page_view_widget.dart
  lib/product/view/add_product_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔗feature, ⚙️config

#65 [Feature]내 게시글 & 찜 API 연결
  lib/model/data/inquiry/inquiry_model.dart
  lib/model/data/inquiry/inquiry_model.g.dart
  lib/model/data/mypage/like_model.dart
  lib/model/data/mypage/like_model.g.dart
  lib/model/data/mypage/myproduct_model.dart
  lib/model/data/mypage/myproduct_model.g.dart
  lib/mypage/component/like_list_item.dart
  lib/mypage/component/post_list_item.dart
  lib/mypage/view/likelist_screen.dart
  lib/mypage/view/mypost_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/presenter/mypage/mypage_service.dart
Labels: 🔗feature

#70 [Feature] 토큰 재발급
  lib/model/network/api_manager.dart
  lib/model/network/cutsom_interceptor.dart
Labels: 🔗feature

#73 [Fix] 토큰 재발급 요청 시 header를 no auth로 수정
  lib/model/network/cutsom_interceptor.dart
Labels: 🛠fix

#74 [Fix] 상품 관련 수정사항 처리
  lib/common/const/constants.dart
  lib/common/view/search_screen.dart
  lib/presenter/shopping/shopping_service.dart
  lib/product/component/product_img_page_view_widget.dart
  lib/product/view/add_product_screen.dart
  lib/product/view/product_detail_screen.dart
  lib/shopping/component/category_list_item.dart
  lib/shopping/component/popular_list_item.dart
  lib/shopping/component/tabbar_widget.dart
  lib/shopping/view/shopping_screen.dart
Labels: 🛠fix

#75 [Feature] 검색, 상품 수정 API 연결
  lib/common/const/constants.dart
  lib/common/layout/pick_img_widget.dart
  lib/common/layout/purple_outlined_text_field.dart
  lib/common/view/search_screen.dart
  lib/model/data/shopping/search_result_model.dart
  lib/model/data/shopping/search_result_model.g.dart
  lib/presenter/common/search_service.dart
  lib/presenter/shopping/shopping_service.dart
  lib/product/component/custom_dropdown_button.dart
  lib/product/component/product_detail_appbar.dart
  lib/product/view/add_product_screen.dart
  lib/product/view/product_detail_screen.dart
  lib/shopping/component/category_list_item.dart
  lib/shopping/component/popular_list_item.dart
  pubspec.lock
Labels: 🔗feature

#76 [Feature]내 정보 & 마이페이지 API 연결
  lib/home/component/product_list_item.dart
  lib/model/data/myinfo/myinfo_model.dart
  lib/model/data/myinfo/myinfo_model.g.dart
  lib/model/data/mypage/like_model.g.dart
  lib/model/data/order/order_list_model.dart
  lib/model/data/order/order_list_model.g.dart
  lib/myinfo/view/myinfo_screen.dart
  lib/mypage/view/mypage_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/presenter/myinfo/myinfo_service.dart
  lib/presenter/mypage/mypage_service.dart
  lib/review/view/add_review_screen.dart
Labels: 🔗feature

#77 [Feature] 로그인 시 유저 타입값을 로컬 스토리지에 저장
  lib/model/network/api_manager.dart
  lib/presenter/auth/login_service.dart
Labels: 🔗feature

#78 [Feature]유저 타입 별 문의하기
  asset/icons/common/message.svg
  lib/common/const/constants.dart
  lib/cs/view/admin_detail_inquiry_screen.dart
  lib/cs/view/detail_inquiry_screen.dart
  lib/cs/view/service_center_screen.dart
  lib/mypage/view/notificationlist_screen.dart
  lib/mypage/view/order_list_tab.dart
Labels: 🔗feature

#80 [Config, Feature] PermissionHandler를 이용한 알림 권한 확인 및 요청 추가
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  lib/auth/view/login_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔗feature, ⚙️config

#81 [Config] deviceToken 추출을 위한 FCM 관련 라이브러리 추가
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Runner.entitlements
  pubspec.lock
  pubspec.yaml
Labels: ⚙️config

#79 [Feature] 알림받기 추가
  lib/myinfo/view/myinfo_screen.dart
Labels: 🔗feature

#82 [Feature] 로그인 시 알림 허용 여부에 따라 deviceToken 포함
  lib/auth/view/login_screen.dart
  lib/model/data/auth/login_model.dart
  lib/model/data/auth/login_model.g.dart
  lib/presenter/auth/login_service.dart
Labels: 🔗feature
