Repository PSR-Co/FRONTEND, pull requests merged in 2023-09, with the labels that each got.

#84 [Feature] 회원가입 요청에 deviceToken 값 추가
  lib/auth/view/signup/set_profile_screen.dart
  lib/main.dart
  lib/presenter/auth/signup_service.dart
Labels: 🔗feature

#85 [Feature]문의하기 관리자 답변 등록 & 삭제 API 연결
  lib/cs/view/admin_detail_inquiry_screen.dart
  lib/cs/view/service_center_screen.dart
  lib/model/data/inquiry/delete_inquiry_answer_model.dart
  lib/model/data/inquiry/delete_inquiry_answer_model.g.dart
  lib/model/data/myinfo/myinfo_model.g.dart
  lib/mypage/view/order_list_tab.dart
  lib/presenter/inquiry/inquiry_service.dart
Labels: 🔗feature

#86 [Fix] 쇼핑 메인 화면 UI 수정사항 처리
  lib/common/const/constants.dart
  lib/shopping/component/category_list_item.dart
  lib/shopping/component/popular_list_item.dart
  lib/shopping/component/tabbar_widget.dart
Labels: 🛠fix

#87 [Feature] 1:1 요청 완료 화면 UI 구현(화면연결 제외)
  lib/order/view/add_order_screen.dart
  lib/order/view/complete_order_screen.dart
Labels: 🔗feature

#89 [Feature] 상품 추가 화면 내 이미지 추가 관련 기능 구현
  ios/Podfile.lock
  lib/common/layout/pick_img_widget.dart
  lib/common/layout/purple_outlined_text_field.dart
  lib/presenter/common/ImageService.dart
  lib/product/view/add_product_screen.dart
Labels: 🔗feature

#90 [Fix] 회원가입 관련 수정사항 반영
  lib/auth/view/signup/set_profile_screen.dart
  lib/presenter/auth/signup_service.dart
Labels: 🛠fix

#91 [Feature] 카카오톡 공유하기 구현 중
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  lib/common/view/splash_screen.dart
  lib/main.dart
  lib/presenter/shopping/kakao_share_with_dynamic_link.dart
  lib/product/component/product_detail_appbar.dart
  lib/product/view/product_detail_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔗feature

#92 [Config] pub upgrade 적용
  ios/Podfile.lock
  pubspec.lock
Labels: ⚙️config

#93 [Feature]비밀번호 변경 API 연결
  lib/model/data/myinfo/myinfo_model.dart
  lib/model/data/myinfo/myinfo_model.g.dart
  lib/myinfo/view/change_pw_screen.dart
  lib/myinfo/view/myinfo_screen.dart
  lib/mypage/view/mypage_screen.dart
  lib/presenter/myinfo/myinfo_service.dart
Labels: 🔗feature

#94 [Config] 앱 아이콘 추가 및 이름 변경
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  asset/images/app_icon.png
  flutter_launcher_icons.yaml
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.lock
  pubspec.yaml
Labels: ⚙️config

#96 [Feature] 회원탈퇴 & 로그아웃 API 연결
  ios/Runner.xcodeproj/project.pbxproj
  lib/common/layout/circular_progress_indicator.dart
  lib/common/view/splash_screen.dart
  lib/cs/component/inquiry_list.dart
  lib/cs/component/notice_list.dart
  lib/cs/view/admin_detail_inquiry_screen.dart
  lib/home/view/home_screen.dart
  lib/model/data/myinfo/myinfo_model.dart
  lib/model/data/myinfo/myinfo_model.g.dart
  lib/myinfo/component/common_dialog.dart
  lib/myinfo/component/second_dialog.dart
  lib/myinfo/view/logout_dialog.dart
  lib/myinfo/view/myinfo_screen.dart
  lib/myinfo/view/withdrawal_dialog.dart
  lib/mypage/view/mypage_screen.dart
  lib/presenter/home/home_service.dart
  lib/presenter/myinfo/myinfo_service.dart
Labels: 🔗feature

#97 [Refactor] 알림 설정 클래스 분리
  lib/common/layout/circular_progress_indicator.dart
  lib/myinfo/view/myinfo_screen.dart
  lib/myinfo/view/set_notification.dart
Labels: ♻️refactor

#98 [Fix] 쇼핑 및 상품 관련 수정사항 처리
  lib/common/view/splash_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/order/view/add_order_screen.dart
  lib/order/view/complete_order_screen.dart
  lib/product/component/product_img_page_view_widget.dart
  lib/product/component/product_info_widget.dart
  lib/product/component/seller_info_widget.dart
  lib/product/component/seller_product_list_item.dart
  lib/product/view/add_product_screen.dart
  lib/review/view/add_review_screen.dart
  lib/review/view/review_screen.dart
  lib/shopping/component/category_list_item.dart
  lib/shopping/component/popular_list_item.dart
Labels: 🛠fix

#100 [Fix] 요청 수정 결과 다이얼로그 추가
  lib/myinfo/view/withdrawal_dialog.dart
  lib/mypage/view/detail_order_screen.dart
  lib/order/component/order_dialog.dart
  lib/presenter/order/order_service.dart
Labels: 🛠fix

#101 [Fix] Auth 관련 수정사항 처리
  lib/auth/component/input_account_info.dart
  lib/auth/component/input_user_info.dart
  lib/auth/component/reset_password.dart
  lib/auth/view/find_id_screen.dart
  lib/auth/view/find_pw_screen.dart
  lib/auth/view/login_screen.dart
  lib/auth/view/signup/agree_terms_screen.dart
  lib/auth/view/signup/input_accout_info_screen.dart
  lib/auth/view/signup/input_business_info_screen.dart
  lib/auth/view/signup/input_user_info_screen.dart
  lib/auth/view/signup/select_role_screen.dart
  lib/auth/view/signup/set_profile_screen.dart
Labels: 🛠fix

#102 [Fix] 요청하기 화면 내 화면터치 시 키보드 다운 추가
  lib/order/view/add_order_screen.dart
Labels: 🛠fix

#103 [Feature] 마이페이지 내 알림 변경 구현 중
  lib/myinfo/view/set_notification.dart
Labels: 🔗feature

#95 [Config] iOS scheme을 debug에서 release로 변경
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Labels: ⚙️config

#104 [Fix]요청 관련 수정
  ios/Runner.xcodeproj/project.pbxproj
  lib/cs/view/inquiry_screen.dart
  lib/myinfo/view/change_pw_screen.dart
  lib/mypage/view/detail_order_screen.dart
Labels: 🛠fix

#105 [Config] 안드로이드 배포를 위한 build.gradle 수정
  android/app/build.gradle
Labels: ⚙️config

#106 [Config, Fix] iOS bundle id 원복
  ios/Runner.xcodeproj/project.pbxproj
Labels: ⚙️config, 🛠fix

#107 [Fix] 로그인 요청 시 로딩 애니메이션 추가 및 권한 요청 로직 순서 변경
  lib/auth/view/login_screen.dart
Labels: 🛠fix

#109 [Fix] 회원가입 완료 및 프로필 편집 시 로딩 애니메이션 추가, 권한 요청 로직 순서 수정
  lib/auth/view/signup/set_profile_screen.dart
Labels: 🛠fix

#116 [Fix]home 관련 수정사항
  lib/common/layout/circular_progress_indicator.dart
  lib/common/layout/detail_bar_layout.dart
  lib/cs/view/detail_notice_screen.dart
  lib/cs/view/notice_screen.dart
  lib/home/component/notice_list_content.dart
  lib/home/view/home_screen.dart
  lib/model/data/cs/notice_model.dart
  lib/model/data/cs/notice_model.g.dart
Labels: 🛠fix

#118 [Fix]홈 관련 1차 qa 수정사항
  lib/auth/view/login_screen.dart
  lib/common/layout/detail_bar_layout.dart
  lib/common/layout/main_appbar_layout.dart
  lib/common/view/root_tab.dart
  lib/common/view/splash_screen.dart
  lib/home/component/best_list_item.dart
  lib/home/component/outlined_btn.dart
  lib/home/component/product_list_item.dart
  lib/home/component/recent_list_item.dart
  lib/home/view/home_screen.dart
  lib/shopping/view/shopping_screen.dart
  test/widget_test.dart
Labels: 🛠fix

#115 [Fix] 파이어베이스에 이미지 업로드 시,파일명 랜덤 문자열로 지정되도록 수정
  lib/presenter/common/ImageService.dart
Labels: 🛠fix

#119 [Fix] Auth 관련 QA 수정사항 반영
  android/app/src/main/AndroidManifest.xml
  asset/icons/common/circle_plus_icon.svg
  lib/auth/component/account_input_text_field.dart
  lib/auth/component/input_account_info.dart
  lib/auth/component/input_user_info.dart
  lib/auth/component/reset_password.dart
  lib/auth/view/find_id_screen.dart
  lib/auth/view/find_pw_screen.dart
  lib/auth/view/login_screen.dart
  lib/auth/view/signup/agree_terms_screen.dart
  lib/auth/view/signup/input_user_info_screen.dart
  lib/auth/view/signup/select_interest_screen.dart
  lib/auth/view/signup/set_profile_screen.dart
  lib/common/layout/purple_outlined_text_field.dart
  lib/home/view/home_screen.dart
  lib/model/data/auth/user_model.dart
  lib/model/data/auth/user_model.g.dart
  lib/model/data/myinfo/myinfo_model.g.dart
  lib/model/network/cutsom_interceptor.dart
  lib/presenter/auth/signup_service.dart
  lib/presenter/auth/user_service.dart
Labels: 🛠fix

#120 [Fix] 요청관련 1차 qa 수정
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/common/layout/large_detail_bar_layout.dart
  lib/common/view/body_tab.dart
  lib/cs/view/faq_screen.dart
  lib/cs/view/service_center_screen.dart
  lib/home/view/home_screen.dart
  lib/mypage/component/action_btn.dart
  lib/mypage/component/detail_order_textfield_form.dart
  lib/mypage/view/detail_order_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/mypage/view/order_list_tab.dart
  lib/order/component/order_dialog.dart
Labels: 🛠fix

#123 [Fix] products 관련 QA 수정사항 반영
  lib/common/const/constants.dart
  lib/common/view/body_tab.dart
  lib/common/view/search_screen.dart
  lib/model/data/review/review_model.dart
  lib/model/data/review/review_model.g.dart
  lib/model/network/cutsom_interceptor.dart
  lib/mypage/view/order_list_screen.dart
  lib/order/view/add_order_screen.dart
  lib/order/view/complete_order_screen.dart
  lib/product/component/bottom_navigation_widget.dart
  lib/product/component/product_detail_appbar.dart
  lib/product/component/product_detail_widget.dart
  lib/product/component/product_info_widget.dart
  lib/product/component/review_list_item.dart
  lib/product/view/add_product_screen.dart
  lib/product/view/declaration_dialog.dart
  lib/product/view/product_detail_screen.dart
  lib/product/view/seller_profile_screen.dart
  lib/review/component/review_info_widget.dart
  lib/review/component/review_item_widget.dart
  lib/review/component/user_profile_img_widget.dart
  lib/review/view/add_review_screen.dart
  lib/shopping/component/category_list_item.dart
  lib/shopping/component/popular_list_item.dart
  lib/shopping/component/tabbar_widget.dart
Labels: 🛠fix

#124 [Fix] 요청 관련 수정된 API 적용
  lib/mypage/component/detail_order_textfield_form.dart
  lib/mypage/view/detail_order_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/order/component/order_dialog.dart
  lib/presenter/order/order_service.dart
Labels: 🛠fix

#125 [Feature] 마이페이지 내 알림 설정 구현
  lib/model/data/myinfo/myinfo_model.dart
  lib/model/data/myinfo/myinfo_model.g.dart
  lib/myinfo/view/set_notification.dart
  lib/presenter/myinfo/myinfo_service.dart
Labels: 🔗feature

#127 [Fix] 요청 상태 수정 후 새로고침 반영
  lib/common/view/body_tab.dart
  lib/cs/view/service_center_screen.dart
  lib/mypage/view/order_list_screen.dart
  lib/mypage/view/order_list_tab.dart
  lib/order/component/order_dialog.dart
Labels: 🛠fix
