Repository PSR-Co/FRONTEND, pull requests merged in 2023-12, with the labels that each got.

#135 [Fix] 공유하기 기본 이미지 변경 및 appstoreId 추가
  lib/presenter/shopping/kakao_share_with_dynamic_link.dart
Labels: 🛠fix

#136 [Feature] 채팅 UI 구현
  asset/icons/chat/send.svg
  ios/Podfile
  ios/Podfile.lock
  lib/chat/component/chat_list_item.dart
  lib/chat/component/chat_message_list_item.dart
  lib/chat/view/chat_room_screen.dart
  lib/chat/view/chat_screen.dart
  lib/common/const/colors.dart
  lib/mypage/view/mypage_screen.dart
  lib/presenter/chat/chat_service.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔗feature

#137 [Fix] 쪽지 기능 준비 멘트 재적용
  lib/chat/view/chat_screen.dart
Labels: 🪛chore
